a = int(input('Input your number: '))
print(f'Double the number of {a} = {(lambda x: x * 2)(a)}')
print(f'Triple the number of {a} = {(lambda x: x * 3)(a)}')
print(f'Quadruple the number of {a} = {(lambda x: x * 4)(a)}')
print(f'Quintuple the number of {a} = {(lambda x: x * 5)(a)}')